### ISSUE TITLE
Unable to discover M2 Reader

### ISSUE THREAD

**Issue by anthonysette** [awazgyawali/flutter_stripe_terminal#1]
Hey @awazgyawali,

I love this contribution to the Flutter community it was much needed. I am however experiencing issues when I attempt to connect to the Stripe M2 Reader. 

When scanning for devices the reader just does not show up, what readers have you tested with? In simulated mode, it all works, but the actual Bluetooth reader is not being discovered.

Let me know!

**Comment by anthonysette** [comment]
Here are the logs:

```IAPAppRegisterClient: capabilities 0x8020
IAPAppRegisterClient: __eaClientRegisterediapd 0 -> 1
IAPAppRegisterClient: __eaClientRegisterediap2d 0 -> 1
IAPDHasLaunched: kIAPAvailableNotification iapdAvailableState 100 -> 1
IAPAppRegisterClient: __eaiapdHasClientID 0, IAPDHasLaunched 1
IAP2DHasLaunched: kIAP2AvailableNotification iap2dAvailableState 100 -> 0
IAPAppRegisterClient: __eaiap2dHasClientID 0, IAP2DHasLaunched 0
IAPAppRegisterClient: registerWasSuccessful 1
-[EAAccessoryManager _initFromSingletonCreationMethod] initializing (0x281ac3480) with uuid 5E8DC687-07CC-481B-A0E4-2B086861BD33
-[EAAccessoryManager _initFromSingletonCreationMethod] isRunningOnMac
initialConnectedAccessories count 0
_connectedAccessories (0)
Done attaching initialConnectedAccessories
IAPAppConnectedAccessories: __eaClientHasCheckedForConnectedAccessories 0 -> 1
IAPAppConnectedAccessories: IAPDHasLaunched 1, IAP2DHasLaunched 0
On: 1065 Unregistering. RegisteredForLocalNotifications Count: 0
On: 1045 RegisteredForLocalNotifications Count: 1
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0
Returning connectedAccessories count 0

**Comment by awazgyawali** [comment]
Hi @anthonysette, I am glad to hear that you are finding this package useful.

The sad news is that I don't have real M2 device with me to test, I verified the code just by using the simulator (which is bizarre). The true reason I don't have a M2 reader with me is because I live in Nepal and Stripe do not ship items directly to my country.

However, my client has ordered his this week, we are testing the SDK soon. We need this SDK to work more than you do probably. I will keep you posted once I complete my testing on real device and probably come back with new release with a fix.

**Comment by anthonysette** [comment]
Thanks for responding @awazgyawali, I do have an M2 reader on hand. My main reason for reaching out was to see if you had success with the M2 reader because if that was the case I did not want to spend time looking into it since it would have been some improper configuration on my end.

Knowing you have not tested it with an actual reader just yet I will find some time this week to look into it as well and let you know if I find anything 👍

**Comment by MichaelCadavillo** [comment]
Hi,
I was also working on integrating one of our apps with an M2 reader.
Have also faced the issue where it was not discovering the device.

Went through the code and found out that it was due to the discovered M2 device not having any data on `originalJSON` field, it was causing an error when parsing.

I've made a [pull request](https://github.com/awazgyawali/flutter_stripe_terminal/pull/3) containing some null checks for that field.

Kindly test it once to check if it works on your end as well.

**Comment by awazgyawali** [comment]
Hi @MichaelCadavillo 

Thank you for your contribution, however I just made a major release with the fixes you sent on the PR. It looks like we worked at the same period.

Please use the latest version (v1.2.0) and let me know if that worked for you.

Also please consider rebasing with master and updating the PR if I have missed anything.

https://github.com/awazgyawali/flutter_stripe_terminal/releases/tag/v1.2.0
